### PR TITLE
Working: Make Grubbs test work

### LINKED ISSUE #11: `N` never defined in the Grubbs test
When the Grubbs test was added in b51dd05, `N` was never defined.

### PR DESCRIPTION
**Pull request by theavey**
This should fix #11 by defining `N`.

### CODE REVIEW

**Comment by theavey** [comment]
This is not ready to be merged yet.

**Comment by maximtrp** [comment]
@theavey Thank you! I guess `len(x)` is enough. What else are you planning to do?

**Comment by theavey** [comment]
There are other terms that need defining in the function, and I haven't had a chance to finish fixing it yet.

**Comment by maximtrp** [comment]
I've found what you were talking about. Will finish it myself. Thank you!

**Pull request merged**
